# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created: Mon Dec  1 16:36:20 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1189, 596)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.gridlayout = QtWidgets.QGridLayout(MainWindow)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setContentsMargins(9, 9, 9, 9)
        self.gridlayout.setObjectName("gridlayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lavapolovica = QtWidgets.QHBoxLayout()
        self.lavapolovica.setObjectName("lavapolovica")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelPredloha = QtWidgets.QLabel(MainWindow)
        self.labelPredloha.setObjectName("labelPredloha")
        self.verticalLayout_6.addWidget(self.labelPredloha)
        self.plainTextEditPredloha = QtWidgets.QPlainTextEdit(MainWindow)
        self.plainTextEditPredloha.setPlainText("")
        self.plainTextEditPredloha.setObjectName("plainTextEditPredloha")
        self.verticalLayout_6.addWidget(self.plainTextEditPredloha)
        self.lavapolovica.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelMeranie = QtWidgets.QLabel(MainWindow)
        self.labelMeranie.setObjectName("labelMeranie")
        self.verticalLayout_7.addWidget(self.labelMeranie)
        self.plainTextEditMeranie = QtWidgets.QPlainTextEdit(MainWindow)
        self.plainTextEditMeranie.setObjectName("plainTextEditMeranie")
        self.verticalLayout_7.addWidget(self.plainTextEditMeranie)
        self.lavapolovica.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addLayout(self.lavapolovica)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelSubor2 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubor2.sizePolicy().hasHeightForWidth())
        self.labelSubor2.setSizePolicy(sizePolicy)
        self.labelSubor2.setMinimumSize(QtCore.QSize(60, 0))
        self.labelSubor2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubor2.setObjectName("labelSubor2")
        self.horizontalLayout_3.addWidget(self.labelSubor2)
        self.lineEditSubor2 = QtWidgets.QLineEdit(MainWindow)
        self.lineEditSubor2.setObjectName("lineEditSubor2")
        self.horizontalLayout_3.addWidget(self.lineEditSubor2)
        self.pushButtonSubor2 = QtWidgets.QPushButton(MainWindow)
        self.pushButtonSubor2.setObjectName("pushButtonSubor2")
        self.horizontalLayout_3.addWidget(self.pushButtonSubor2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSubor1 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubor1.sizePolicy().hasHeightForWidth())
        self.labelSubor1.setSizePolicy(sizePolicy)
        self.labelSubor1.setMinimumSize(QtCore.QSize(60, 0))
        self.labelSubor1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubor1.setObjectName("labelSubor1")
        self.horizontalLayout_2.addWidget(self.labelSubor1)
        self.lineEditSubor1 = QtWidgets.QLineEdit(MainWindow)
        self.lineEditSubor1.setObjectName("lineEditSubor1")
        self.horizontalLayout_2.addWidget(self.lineEditSubor1)
        self.pushButtonSubor1 = QtWidgets.QPushButton(MainWindow)
        self.pushButtonSubor1.setObjectName("pushButtonSubor1")
        self.horizontalLayout_2.addWidget(self.pushButtonSubor1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelZachytne = QtWidgets.QLabel(MainWindow)
        self.labelZachytne.setObjectName("labelZachytne")
        self.verticalLayout_9.addWidget(self.labelZachytne)
        self.tableWidgetZachytne = QtWidgets.QTableWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetZachytne.sizePolicy().hasHeightForWidth())
        self.tableWidgetZachytne.setSizePolicy(sizePolicy)
        self.tableWidgetZachytne.setMinimumSize(QtCore.QSize(330, 0))
        self.tableWidgetZachytne.setObjectName("tableWidgetZachytne")
        self.tableWidgetZachytne.setColumnCount(0)
        self.tableWidgetZachytne.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tableWidgetZachytne)
        self.pushButtonObnovit = QtWidgets.QPushButton(MainWindow)
        self.pushButtonObnovit.setObjectName("pushButtonObnovit")
        self.verticalLayout_9.addWidget(self.pushButtonObnovit)
        self.pushButtonVsetky = QtWidgets.QPushButton(MainWindow)
        self.pushButtonVsetky.setObjectName("pushButtonVsetky")
        self.verticalLayout_9.addWidget(self.pushButtonVsetky)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelChyba = QtWidgets.QLabel(self.tab)
        self.labelChyba.setObjectName("labelChyba")
        self.horizontalLayout_4.addWidget(self.labelChyba)
        self.lineEditChyba = QtWidgets.QLineEdit(self.tab)
        self.lineEditChyba.setAcceptDrops(False)
        self.lineEditChyba.setInputMask("")
        self.lineEditChyba.setReadOnly(True)
        self.lineEditChyba.setClearButtonEnabled(False)
        self.lineEditChyba.setObjectName("lineEditChyba")
        self.horizontalLayout_4.addWidget(self.lineEditChyba)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.plainTextEditTransformovane = QtWidgets.QPlainTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditTransformovane.sizePolicy().hasHeightForWidth())
        self.plainTextEditTransformovane.setSizePolicy(sizePolicy)
        self.plainTextEditTransformovane.setMinimumSize(QtCore.QSize(300, 0))
        self.plainTextEditTransformovane.setObjectName("plainTextEditTransformovane")
        self.gridLayout.addWidget(self.plainTextEditTransformovane, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEditTransformovane_2 = QtWidgets.QPlainTextEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditTransformovane_2.sizePolicy().hasHeightForWidth())
        self.plainTextEditTransformovane_2.setSizePolicy(sizePolicy)
        self.plainTextEditTransformovane_2.setMinimumSize(QtCore.QSize(300, 0))
        self.plainTextEditTransformovane_2.setObjectName("plainTextEditTransformovane_2")
        self.gridLayout_2.addWidget(self.plainTextEditTransformovane_2, 8, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelChyba_2 = QtWidgets.QLabel(self.tab_2)
        self.labelChyba_2.setObjectName("labelChyba_2")
        self.horizontalLayout_5.addWidget(self.labelChyba_2)
        self.lineEditChyba_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditChyba_2.setAcceptDrops(False)
        self.lineEditChyba_2.setInputMask("")
        self.lineEditChyba_2.setReadOnly(True)
        self.lineEditChyba_2.setClearButtonEnabled(False)
        self.lineEditChyba_2.setObjectName("lineEditChyba_2")
        self.horizontalLayout_5.addWidget(self.lineEditChyba_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton3bod = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton3bod.setObjectName("radioButton3bod")
        self.horizontalLayout_7.addWidget(self.radioButton3bod)
        self.lineEdit3bod = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit3bod.setReadOnly(True)
        self.lineEdit3bod.setObjectName("lineEdit3bod")
        self.horizontalLayout_7.addWidget(self.lineEdit3bod)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton2bod = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton2bod.setObjectName("radioButton2bod")
        self.horizontalLayout_8.addWidget(self.radioButton2bod)
        self.lineEdit2bod = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit2bod.setReadOnly(True)
        self.lineEdit2bod.setObjectName("lineEdit2bod")
        self.horizontalLayout_8.addWidget(self.lineEdit2bod)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton1bod = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton1bod.setChecked(False)
        self.radioButton1bod.setObjectName("radioButton1bod")
        self.horizontalLayout_9.addWidget(self.radioButton1bod)
        self.lineEdit1bod = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit1bod.setReadOnly(True)
        self.lineEdit1bod.setObjectName("lineEdit1bod")
        self.horizontalLayout_9.addWidget(self.lineEdit1bod)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.radioButtonNA = QtWidgets.QRadioButton(self.tab_2)
        self.radioButtonNA.setChecked(True)
        self.radioButtonNA.setObjectName("radioButtonNA")
        self.gridLayout_2.addWidget(self.radioButtonNA, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.labelTransformovane = QtWidgets.QLabel(MainWindow)
        self.labelTransformovane.setObjectName("labelTransformovane")
        self.verticalLayout_8.addWidget(self.labelTransformovane)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelPresnost = QtWidgets.QLabel(MainWindow)
        self.labelPresnost.setEnabled(True)
        self.labelPresnost.setObjectName("labelPresnost")
        self.horizontalLayout.addWidget(self.labelPresnost)
        self.spinBoxPresnost = QtWidgets.QSpinBox(MainWindow)
        self.spinBoxPresnost.setEnabled(True)
        self.spinBoxPresnost.setMouseTracking(False)
        self.spinBoxPresnost.setAcceptDrops(True)
        self.spinBoxPresnost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxPresnost.setReadOnly(False)
        self.spinBoxPresnost.setMaximum(999)
        self.spinBoxPresnost.setProperty("value", 20)
        self.spinBoxPresnost.setObjectName("spinBoxPresnost")
        self.horizontalLayout.addWidget(self.spinBoxPresnost)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.pushButtonPrepocitat = QtWidgets.QPushButton(MainWindow)
        self.pushButtonPrepocitat.setIconSize(QtCore.QSize(124, 52))
        self.pushButtonPrepocitat.setObjectName("pushButtonPrepocitat")
        self.verticalLayout_8.addWidget(self.pushButtonPrepocitat)
        self.pushButtonUkazka = QtWidgets.QPushButton(MainWindow)
        self.pushButtonUkazka.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonUkazka.setObjectName("pushButtonUkazka")
        self.verticalLayout_8.addWidget(self.pushButtonUkazka)
        self.pushButtonUlozit = QtWidgets.QPushButton(MainWindow)
        self.pushButtonUlozit.setObjectName("pushButtonUlozit")
        self.verticalLayout_8.addWidget(self.pushButtonUlozit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6.setStretch(0, 6)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 3)
        self.gridlayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transformacia Zameranych Bodov"))
        self.labelPredloha.setText(_translate("MainWindow", "Body Predlohy"))
        self.labelMeranie.setText(_translate("MainWindow", "Body z Merania"))
        self.labelSubor2.setText(_translate("MainWindow", "Vstup 2\n"
"Meranie"))
        self.pushButtonSubor2.setText(_translate("MainWindow", "Hladat"))
        self.labelSubor1.setText(_translate("MainWindow", "Vstup 1\n"
"Predloha"))
        self.pushButtonSubor1.setText(_translate("MainWindow", "Hladat"))
        self.labelZachytne.setText(_translate("MainWindow", "Zachytne Body ( z Merania ) [ Vyber Riadok : Ctrl + Left Click ]"))
        self.pushButtonObnovit.setText(_translate("MainWindow", "Obnovit Tabulku"))
        self.pushButtonVsetky.setText(_translate("MainWindow", "Vyber Vsetky"))
        self.labelChyba.setText(_translate("MainWindow", "Chyba vypoctu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "LSQ"))
        self.labelChyba_2.setText(_translate("MainWindow", "Chyba vypoctu"))
        self.radioButton3bod.setText(_translate("MainWindow", "3. bod"))
        self.radioButton2bod.setText(_translate("MainWindow", "2. bod"))
        self.radioButton1bod.setText(_translate("MainWindow", "1. bod"))
        self.radioButtonNA.setText(_translate("MainWindow", "Ziaden vyber"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Posun, Rotacia, Rotacia"))
        self.labelTransformovane.setText(_translate("MainWindow", "Transformovane Body"))
        self.labelPresnost.setText(_translate("MainWindow", "Presnost - Pocet Desatinnych miest"))
        self.pushButtonPrepocitat.setText(_translate("MainWindow", "Prepocitat"))
        self.pushButtonUkazka.setText(_translate("MainWindow", "Ukazka"))
        self.pushButtonUlozit.setText(_translate("MainWindow", "Ulozit"))

